# Generated by Django 5.2.4 on 2025-07-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_verification_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
